# Generated by Django 4.2.3 on 2023-08-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('published', models.DateField()),
                ('writer', models.CharField(max_length=100)),
                ('penciler', models.CharField(max_length=100)),
                ('cover', models.CharField(max_length=100)),
                ('img_url', models.URLField()),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
    ]
