# Generated by Django 4.2.3 on 2023-08-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_votes_vote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='vote',
            name='comment',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='vote',
            name='rating',
            field=models.CharField(choices=[('1', 'Poor'), ('2', 'Alright'), ('3', 'Good'), ('4', 'Very Good'), ('5', 'Amazing')], default='1', max_length=1),
        ),
    ]
