# Generated by Django 4.2.3 on 2023-08-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='characters',
            field=models.ManyToManyField(to='main_app.character'),
        ),
    ]
