# Generated by Django 4.2.3 on 2023-08-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_comic_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
